### ISSUE TITLE
Allow GSSP\'s to be added though configuraton

### ISSUE THREAD

**Issue by phavekes** [OpenConext/Stepup-SelfService#401]
[This issue is imported from pivotal - Originaly created at May 2, 2017 by Pieter van der Meulen](https://www.pivotaltracker.com/story/show/144698955)

There are currently two [GSSP](https://github.com/OpenConext/Stepup-Gateway/blob/develop/docs/GSSP.md)s available: tiqr and biometric. Adding another GSSP requires configuration and code changes. As an operator of a Stepup installation I want to be able to add additional GSSPs through configuraton only.

Regarding logo\'s and text being configurable. See chore: https://www.pivotaltracker.com/story/show/100037372

Related chore: https://www.pivotaltracker.com/story/show/90281914
Estimation: 1.5d

**Comment by phavekes** [comment]
The first target is that modification of `samlstepupproviders.yml` in the SS/RA/GW should be enough to fully manage GSSPs. In the future it should be possible to manage this through the management API and propagate configuration through the database/internal API\'s.

This means that any GSSP specific code should be changed such that it no longer is specific (see issue linked in description).

It also means that language (translations for e.g. buttons in the SS/RA) and images (For second factor selection screen) should be configurable (Note: this is not an exhaustive list, verify what must be configurable). (Daan van Renterghem - May 15, 2017)

**Comment by phavekes** [comment]
In the SS `samlstepupproviders.yml`, when making the GSSP configurable like this:

samlstepupprovides.yml
```
surfnet_stepup_self_service_saml_stepup_provider:
     ...
    providers:
        tiqr:
            hosted:
                ...
            remote:
                ...
            view_config:
                loa: %gssp_tiqr_loa%
                logo: %gssp_tiqr_logo%
                alt: %gssp_tiqr_alt%
                title: %gssp_tiqr_title%
                description: %gssp_tiqr_description%
                button_use: %gssp_tiqr_button_use%
```

samlstepupproviders_parameters.yml
```
    ...
    gssp_tiqr_loa: 3
    gssp_tiqr_logo: \'/images/second-factor/tiqr.png\'
    gssp_tiqr_alt: \'ss.registration.selector.tiqr.alt\'
    gssp_tiqr_title: \'ss.registration.selector.tiqr.title\'
    gssp_tiqr_description: \'ss.registration.selector.tiqr.description\'
    gssp_tiqr_button_use: \'ss.registration.selector.tiqr.button.use\'
```

This still leaves the problem of the text translations that need to take place. 

@pmeulen, do you want to make the text translations in the yml file? Like so:

```
gssp_tiqr_title: 
    - nl: \'Tiqr\'
    - en: \'TiQr\'
```

Or keep using the `JMSTranslationBundle` for the gssf text translations, as we do now? This includes adding the  translations to the `Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/translations.twig`. (Michiel Kodde - May 29, 2017)

**Comment by phavekes** [comment]
Having to update the translations (which are currently part of the code, part of the tarball used when deploying) when updating the GSSP configuration is defeating the purpose of having the GSSP in configuration. So put them in the config.
There is precedent in the way the support urls in SS/RA can be set in config: https://github.com/OpenConext/Stepup-SelfService/blob/develop/app/config/global_view_parameters.yml.dist

- I would use a plain YAML map, and drop the array, and
- wouldn\'t using tiqr (and maybe even "gssp") in gssp_tiqr_title be redundant? Not a roadblock, Ansible template will happily generate this. But in the quest for simplicity and understandably.
I.e:
```yaml
title: 
    nl: \'Tiqr\'
    en: \'Tiqr\'
```
 (Pieter van der Meulen - May 29, 2017)
